version: '3'
services:
  web:
    build: ./server
    restart: "always"
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - https-certs:/etc/nginx/certs:ro

volumes:
  https-certs:
